/****** Object:  Table [dbo].[Info_MXP_Robot_Alarmes]    Script Date: 2/13/2021 9:27:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Info_Robots_Alarmes](
	[ID] [int] NOT NULL,
	[en] [varchar](255) NULL,
	[ca] [varchar](255) NULL,
	[fr] [varchar](255) NULL,
	[es] [varchar](255) NULL,
	[grup_en] [varchar](50) NULL,
	[grup_ca] [varchar](50) NULL,
	[grup_fr] [varchar](50) NULL,
	[grup_es] [varchar](50) NULL,
 CONSTRAINT [PK_Info_Robots_Alarmes] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Info_MXP_Robot_Info]    Script Date: 2/13/2021 9:26:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Info_Robots_Info](
	[Id] [int] NOT NULL,
	[Ca] [varchar](max) NULL,
	[Es] [varchar](max) NULL,
	[En] [varchar](max) NULL,
 CONSTRAINT [PK_Info_Robots_Info] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

GO
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	0	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	1	,N'	No power. Press the blue button to reset	',N'	Sense potència. Botó blau per rearmar	',N'		',N'	Sin potencia. Pulsador azul para rearmar	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	2	,N'	No air pressure in the robot zone	',N'	Sense pressió daire en la zona robot	',N'		',N'	Sin presión de aire en la zona de robot	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	3	,N'	Error in cabinets I/O module	',N'	Error en el mòdul E/S de larmari	',N'		',N'	Módulo E/S armario en error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	4	,N'	Wizard console is open, close to start manoeuvre	',N'	Pantalla Wizard oberta, sortir de la pantalla per iniciar	',N'		',N'	Pantalla Wizard abierta, salir de la pantalla para iniciar	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	5	,N'	Communication fault between PLC and Robot	',N'	Falla la comunicació entre PLC i robot	',N'		',N'	Fallo comunicación entre PLC y Robot	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	6	,N'	No air pressure in the robot gripper	',N'	Sense pressió daire en la pinça	',N'		',N'	Sin presión de aire en la pinza del robot	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	7	,N'	I/O module in robot gripper cabinet in fault	',N'	Mòdul E/S de la caixa de la pinça en error	',N'		',N'	Módulo E/S caja pinza en error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	8	,N'	Active emergency stop button	',N'	Parada demergència activa	',N'		',N'	Paro de emergencia activo	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	9	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	10	,N'	Robot fault	',N'	Robot en error	',N'		',N'	Robot en error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	11	,N'	Robot key in T1 or T2	',N'	Clau del robot en T1 o T2	',N'		',N'	Llave del robot en T1 o T2	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	12	,N'	Controller key in AUTO and console selector ON, turn it off to continue (FANUC)	',N'	Clau del controlador en AUTO i consola en ON, canviar a OFF (FANUC)	',N'		',N'	Llave del controlador en AUTO i consola en ON, cambiar a OFF (FANUC)	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	13	,N'	Robot key in AUTO mode, needs confirmation in the console (FANUC)	',N'	Clau del robot en AUTO, falta confirmació en la consola (FANUC)	',N'		',N'	Llave del robot en AUTO, falta confirmación en la consola (FANUC)	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	14	,N'	Step by step enabled. Press button STEP to disable (FANUC)	',N'	Step by step activat en la consola del robot. Apretar botó STEP (FANUC)	',N'		',N'	Step by step activado en la consola del robot. Pulsar botón STEP (FANUC)	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	15	,N'	Robot mode selection key has changed	',N'	Clau del robot ha canviat destat	',N'		',N'	Llave del robot ha canviado de estado	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	16	,N'	Robot no tiene MOTORES ON (ABB)	',N'	Robot no té motors ON (ABB)	',N'		',N'	Robot no tiene MOTORES ON (ABB)	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	17	,N'	Robot triggered colision error (ABB)	',N'	Robot en error de col·lissió (ABB)	',N'		',N'	Robot en error de colisión (ABB)	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	18	,N'	Robot has not the drives ready (KUKA)	',N'	Robot no té accionaments ON (Kuka)	',N'		',N'	Robot no tiene accionamientos ON (KUKA)	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	19	,N'	Robot has not the drives ready (Fanuc)	',N'	Robot no té accionaments ON (Fanuc)	',N'		',N'	Robot no tiene accionamientos (Fanuc)	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	20	,N'	The Robot have product in the gripper remove and you make a reset the robot	',N'	El robot te producte a la pinça moure en manual i fer reset del robot	',N'		',N'	El robot tiene producto en la pinza mover en manual para quitarlo, despues hacer reset del robot	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	21	,N'	Robot not referenced in SafeOperation	',N'	Robot no referenciat en el SafeOperation	',N'		',N'	Robot no referenciado en el SafeOperation	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	22	,N'	External Emergency	',N'	Parada demergència externa	',N'		',N'	Paro de emergencia externa	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	23	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	30	,N'	Communication fault between PLC and servodrive (ACOPOS)	',N'	Falla la comunicació entre PLC i servodrive (ACOPOS)	',N'		',N'	Fallo comunicación entre PLC y servodrive (ACOPOS)	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	31	,N'	The servodrive (ACOPOS) is not in READY state	',N'	El servodrive (ACOPOS) no està en estat de READY	',N'		',N'	Els servodrive (ACOPOS) no está en estado READY	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	32	,N'	The Hold button on the robot console has been pressed	',N'	Sha apretat el botó Hold de la consola del robot	',N'		',N'	Se ha apretado el botón Hold de la consola del robot	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	33	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	50	,N'	Waiting for manoeuvre start	',N'	Esperant inici de maniobra	',N'		',N'	Esperando inicio de maniobra	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	51	,N'	Manoeuvre is starting	',N'	Iniciant maniobra	',N'		',N'	Iniciando maniobra	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	52	,N'	Robot program has been restarted	',N'	Programa de robot reiniciat	',N'		',N'	Programa de robot reiniciado	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	53	,N'	Waiting for the robot to go to HOME position	',N'	Esperant que el robot arribi a la posició de HOME	',N'		',N'	Esperando que robot llegue a posición HOME	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	54	,N'	Waiting for new command	',N'	Esperant ordre	',N'		',N'	Esperando orden	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	55	,N'	Robot in manual mode	',N'	Robot en mode manual	',N'		',N'	Robot en modo manual	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	56	,N'	Stop caused by active alarm, message not defined	',N'	Parada causada per alarma activa, missatge no definit	',N'		',N'	Paro por alarma activa, mensaje no definido	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	60	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	70	,N'	Fingers servo: positioning not possible, general error	',N'	Servo dits: impossible posicionar, error general	',N'		',N'	ervo dedos: imposible posicionar, error general	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	71	,N'	Fingers servo: positioning not possible, open message to see the error	',N'	Servo dits: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo dedos: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	72	,N'	Fingers servo: positioning not possible, open message to see the error	',N'	Servo dits: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo dedos: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	73	,N'	Fingers servo: positioning not possible, open message to see the error	',N'	Servo dits: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo dedos: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	74	,N'	Fingers servo: positioning not possible, open message to see the error	',N'	Servo dits: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo dedos: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	75	,N'	Fingers servo: positioning not possible, open message to see the error	',N'	Servo dits: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo dedos: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	76	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	80	,N'	Rubber pads servo: positioning not possible, general error	',N'	Servo mantes: impossible posicionar, error general	',N'		',N'	Servo mantas: imposible posicionar, error general	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	81	,N'	Rubber pads servo: positioning not possible, open message to see the error	',N'	Servo mantes: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo mantas: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	82	,N'	Rubber pads servo: positioning not possible, open message to see the error	',N'	Servo mantes: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo mantas: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	83	,N'	Rubber pads servo: positioning not possible, open message to see the error	',N'	Servo mantes: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo mantas: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	84	,N'	Rubber pads servo: positioning not possible, open message to see the error	',N'	Servo mantes: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo mantas: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	85	,N'	Rubber pads servo: positioning not possible, open message to see the error	',N'	Servo mantes: impossible posicionar, obrir missatge per veure error	',N'		',N'	Servo mantas: imposible posicionar, abrir mensaje para ver error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	86	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	90	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	98	,N'	Right sensor for hook always ON signal	',N'	Sensor grapa dreta avall senyal permanent	',N'		',N'	Sensor grapa derecha arriba señal permanente	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	99	,N'	Left sensor for hook always ON signal	',N'	Sensor grapa esquerra avall senyal permanent	',N'		',N'	Sensor grapa izquerda arriba señal permanente	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	101	,N'	Timeout waiting for left pallet hook open position sensor	',N'	Timeout esperant sensor grapa palet esquerra obert	',N'		',N'	Timeout esperando sensor grapa palet izquierda abierta	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	102	,N'	Timeout waiting for right pallet hook open position sensor	',N'	Timeout esperant sensor grapa palet dreta oberta	',N'		',N'	Timeout esperando sensor grapa palet derecha abierta	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	103	,N'	Timeout waiting for pallet hook open position sensor	',N'	Timeout esperant sensor grapa palet oberta	',N'		',N'	Timeout esperando sensores grapas palet abiertas	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	104	,N'	Timeout waiting for pallet hook pallet position sensor	',N'	Timeout esperant sensor grapa palet en posició de palet	',N'		',N'	Timeout esperando sensor grapas en posición de palet	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	105	,N'	Timeout waiting for pallet hook closed position sensor	',N'	Timeout esperant sensor grapa palet tancada	',N'		',N'	Timeout esperando sensor grapas palet cerradas	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	106	,N'	Timeout waiting for servomotors to be in position	',N'	Timeout esperant servomotors en posició	',N'		',N'	Timeout esperando servomotores posicionados	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	107	,N'	Robot lost the interlayer. Put it manually on L1	',N'	Robot ha perdut intercapa. Posar manualment a la L1	',N'		',N'	Robot ha perdido intercapa. Poner manualmente en L1	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	108	,N'	Robot lost the interlayer. Put it manually on L2	',N'	Robot ha perdut intercapa. Posar manualment a la L2	',N'		',N'	Robot ha perdido intercapa. Poner manualmente en L2	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	109	,N'	Robot lost the interlayer. Put it manually on L3	',N'	Robot ha perdut intercapa. Posar manualment a la L3	',N'		',N'	Robot ha perdido intercapa. Poner manualmente en L3	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	110	,N'	Robot lost the interlayer. Put it manually on L4	',N'	Robot ha perdut intercapa. Posar manualment a la L4	',N'		',N'	Robot ha perdido intercapa. Poner manualmente en L4	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	111	,N'	Timeout waiting for the robot to start, doesnt respond	',N'	Timeout esperant inici del robot, no respon	',N'		',N'	Timeout esperando arranque del robot, no responde	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	112	,N'	Pick error, check the last group of boxes	',N'	Error dagafada, comprovar últim grup de caixes	',N'		',N'	Error de cogida, comprobar último grupo de cajas	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	113	,N'	Robot didnt pick a pallet. Put one manually on L1	',N'	Robot no ha agafat palet. Posar manualment a la L1	',N'		',N'	Robot no ha cogido palet. Poner manualmente en L1	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	114	,N'	Robot didnt pick a pallet. Put one manually on L2	',N'	Robot no ha agafat palet. Posar manualment a la L2	',N'		',N'	Robot no ha cogido palet. Poner manualmente en L2	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	115	,N'	Robot didnt pick a pallet. Put one manually on L3	',N'	Robot no ha agafat palet. Posar manualment a la L3	',N'		',N'	Robot no ha cogido palet. Poner manualmente en L3	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	116	,N'	Robot didnt pick a pallet. Put one manually on L4	',N'	Robot no ha agafat palet. Posar manualment a la L4	',N'		',N'	Robot no ha cogido palet. Poner manualmente en L4	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	117	,N'	Gripper centering device are not closed	',N'	Centrador canats no sha tancat	',N'		',N'	Centrador de canastos no se ha cerrado	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	118	,N'	Gripper centering device are not opened	',N'	entrador canats no sha obert	',N'		',N'	Centrador de canastos no se ha abierto	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	119	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	120	,N'	Finishing pallet	',N'	Finalitzant palet	',N'		',N'	Finalizando palet	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	121	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	150	,N'	Check boxes on stacker	',N'	Revisar caixes apilades	',N'		',N'	Revisar cajas apiladas	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	151	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	160	,N'	Executing frame calibration routine of input tables. Wait for it to finish.	',N'	Executant rutina de calibració de frames de les taules dentrada. Espereu a que finalitzi	',N'		',N'	Ejecutando rutina de calibración de frames de las mesas de entrada. Espere a que finalice	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	161	,N'	Manually move the robot to the calibration start position of the selected input table. Then select the Calibrate_Frames program and start the maneuver.	',N'	Porti el robot manualment a la posició dinici de calibració de la taula dentrada seleccionada. Després, selecccioni el programa Calibrar_Frames i inicii la maniobra.	',N'		',N'	Lleve el robot manualmente a la posición de inicio de calibración de la mesa de entrada seleccionada. Después, selecccionar el programa Calibrar_Frames y inicie la maniobra	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	162	,N'	Completed calibration routine. Confirm changes via VNC to continue.	',N'	Rutina de calibració finalitzada. Confirmar canvis a través de la VNC per continuar.	',N'		',N'	Rutina de calibración finalizada. Confirmar cambios a través de la  VNC  para continuar.	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	163	,N'	Error during calibration procedure. Reset maneuver to restart.	',N'	Error durant el procediment de calibració. Reset de maniobra per reiniciar	',N'		',N'	Error durante el procedimiento de calibración. Reset de maniobra para reiniciar	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	164	,N'	Unable to start calibration of output stations because there is a pallet. Remove the pallets and erase the data.	',N'	No es pot iniciar la calibració de les estacions de sortida perquè hi ha algun palet. Treure els palets i esborrar les dades.	',N'		',N'	No se puede iniciar la calibración de las estaciones de salida porque hay algún palet. Quitar los palillos y borrar los datos.	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	165	,N'	Error calibration sensor during the proces	',N'	Error sensor de calibracio durant la rutina	',N'		',N'	Error sensor de calibración durante la rutina	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	166	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	170	,N'	The robot is waiting for the last boxes in the table to be notified (BN message).	',N'	El robot està esperant a que les últimes caixes de la taula hagin estat notificades (missatge BN).	',N'		',N'	El robot está esperando a que las últimas cajas de la mesa hayan sido notificadas (mensaje BN).	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	171	,N'	Calibration in process	',N'	Calibració en procès	',N'		',N'	Calibración en proceso	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	172	,N'	Gripper check result - OK	',N'	Resultat comprovació pinça - OK	',N'		',N'	Resultado comprobación pinza - OK	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	173	,N'	Gripper check result - Error	',N'	Resultat comprovació pinça - Error	',N'		',N'	Resultado comprobación pinza - Error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	174	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	200	,N'	No interlayers in feeder 1	',N'	No hi ha intercapes a lalimentador 1	',N'		',N'	No hay intercapas en alimentador 1	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	201	,N'	No interlayers in feeder 2	',N'	No hi ha intercapes a lalimentador 2	',N'		',N'	No hay intercapas en alimentador 2	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	202	,N'	No interlayers in feeder 3	',N'	No hi ha intercapes a lalimentador 3	',N'		',N'	No hay intercapas en alimentador 3	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	203	,N'	No pallets in feeder 1	',N'	No hi ha palets a lalimentador 1	',N'		',N'	No hay palets en alimentador 1	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	204	,N'	No pallets in feeder 2	',N'	No hi ha palets a lalimentador 2	',N'		',N'	No hay palets en alimentador 2	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	205	,N'	No pallets in feeder 3	',N'	No hi ha palets a lalimentador 3	',N'		',N'	No hay palets en alimentador 2	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	206	,N'	Collector of rejected boxes full	',N'	Rebuig de caixes ple	',N'		',N'	Rechazo de cajas lleno	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	207	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	210	,N'	Robot picking pallet from feeder 1	',N'	Robot agafant palet de lalimentador 1	',N'		',N'	Robot cogiendo palet del alimentador 1	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	211	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	220	,N'	Robot picking pallet from feeder 2	',N'	Robot agafant palet de lalimentador 2	',N'		',N'	Robot cogiendo palet del alimentador 2	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	221	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	230	,N'	Robot picking pallet from feeder 3	',N'	Robot agafant palet de lalimentador 3	',N'		',N'	Robot cogiendo palet del alimentador 3	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	231	,N'		',N'		',N'		',N'		',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	250	,N'	Check fingers of the gripper	',N'	Comprovar dits	',N'		',N'	Comprovar dedos	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	251	,N'	Robot is outside of the safety zone	',N'	El robot ha sortit de la zona de seguretat	',N'		',N'	El robot ha salido de la zona de seguridad	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (0, N'Desconegut', N'Desconocido', N'Unknown')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (1, N'Interromput per alarma', N'Interrumpido por alarma', N'Aborted by alarm')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (2, N'Falta potència', N'Falta potencia', N'Power off')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (3, N'Falta marxa', N'Falta marcha', N'Waiting start')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (4, N'Canvi de format', N'Cambio de formato', N'Format change')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (5, N'Esperant order', N'Esperando orden', N'Waiting order')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (6, N'Falta material', N'Falta material', N'Missing material')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (7, N'Restablint', N'Restableciendo', N'Reseting')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (8, N'Estoc davant', N'Stock delante', N'Stock ahead')
INSERT [dbo].[Info_Robots_Info] ([Id], [Ca], [Es], [En]) VALUES (9, N'Paletitzant', N'Paletizando', N'Palletizing')
GO
