GO
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	1	,N'	Disabled	',N'	Desactivat	',N'		',N'	Desactivado	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	2	,N'	No air pressure in stacker zone	',N'	Sense pressió d’aire a la zona apilador	',N'		',N'	Sin presión de aire en la zona apilador	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	3	,N'	Waiting for manoeuvre start	',N'	Esperant inici de maniobra	',N'		',N'	Esperando inicio de maniobra	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	5	,N'	Detector fault: Mdxx.In03	',N'	Error detector Mdxx.In03	',N'		',N'	Fallo detector Mdxx.In03	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	11	,N'	Detector rails fault	',N'	Error detectors de les baranes	',N'		',N'	Fallo detectores barandillas	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	12	,N'	Detector fingers fault	',N'	Error detectors dels dits	',N'		',N'	Fallo detectores dedos	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	15	,N'	Servomotor not referenced	',N'	Servo no referenciat	',N'		',N'	Servo no referenciado	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	16	,N'	Icla not referenced	',N'	Icla no referenciat	',N'		',N'	Icla no referenciado	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	20	,N'	Error Servomotor Up/Down	',N'	Error en el servo Pujar/Baixar	',N'		',N'	Error en el servo Subir/Bajar	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	21	,N'	Stacker heigh error	',N'	Error alçada apilador	',N'		',N'	Error altura apilador	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	25	,N'	Stacker Icla not arrive at position	',N'	Icla no arriba a la posició	',N'		',N'	Icla no llega a la posicion	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	30	,N'	Detector fault: MDxx.In11 and MDxx.In09	',N'	Error detectors MDxx.In11 y Mdxx.In09	',N'		',N'	Fallo detectores MDxx.In11 y Mdxx.In09	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	35	,N'	Detector fault: Mdxx.In04	',N'	Error detector MDxx.In04	',N'		',N'	Fallo detector Mdxx.In04	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	40	,N'	Please check detector: MDxx.In15	',N'	Revisar detector MDxx.In15	',N'		',N'	Revisar detector MDxx.In15	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	45	,N'	Please check detector: MDxx.In02	',N'	Revisar detector MDxx.In02	',N'		',N'	Revisar detector MDxx.In02	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	50	,N'	Stacker servomotor not arrive at position	',N'	Servo apilador no arriba a la posicio	',N'		',N'	Servo apilador no llega a la posicion	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	51	,N'	Stucked box or blocked	',N'	Caixa encallada	',N'		',N'	Caja atascada	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	52	,N'	Turned box or blocked	',N'	Caixa girada	',N'		',N'	Caja girada	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	53	,N'	Box Stacker Paused	',N'	Apilador en Pausa	',N'		',N'	Apilador en Pausa	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	54	,N'	Inverter Error	',N'	Inverter en Error	',N'		',N'	Inverter en Error	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	55	,N'	IcLa position Error	',N'	Error en la posicio del Icla	',N'		',N'	Error en la posicion del Icla	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	56	,N'	Remove the boxes that have come out of the stacker	',N'	Treure les caixes que han sortit de lapilador	',N'		',N'	Sacar las cajas que han salido del apilador	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (	80	,N'	Running	',N'	Funcionant	',N'		',N'	Funcionando	',N'		',N'		',N'		',N'		')
INSERT [dbo].[Info_MXP_Apilador_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (0, N'UNKNOWN', N'purple', N'Desconegut', N'Desconocido', N'Unknown')
INSERT [dbo].[Info_MXP_Apilador_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (1, N'Suspended', N'#3AC93A', N'Esperant', N'Esperando', N'Waiting')
INSERT [dbo].[Info_MXP_Apilador_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (2, N'STOPPED', N'blue', N'Aturat', N'Parado', N'Stopped')
INSERT [dbo].[Info_MXP_Apilador_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (3, N'RESETING', N'#f9feae', N'Restablint', N'Restableciendo', N'Reseting')
INSERT [dbo].[Info_MXP_Apilador_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (4, N'EXECUTE', N'green', N'En funcionament', N'En funcionamiento', N'Running')
INSERT [dbo].[Info_MXP_Apilador_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (5, N'FORMATCHANGE', N'#fec0df', N'Canvi de format', N'Cambio de formato', N'Format changing')
INSERT [dbo].[Info_MXP_Apilador_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (6, N'ABORTED', N'red', N'Interromput', N'Interrumpido', N'Aborted')
INSERT [dbo].[Info_MXP_Apilador_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (7, N'HELD', N'yellow', N'Retingut', N'Retenido', N'Held')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (0, N'Desconegut', N'Desconocido', N'Unknown')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (1, N'Interromput per alarma', N'Interrumpido por alarma', N'Aborted by alarm')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (2, N'Falta potència', N'Falta potencia', N'Power off')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (3, N'Falta marxa', N'Falta marcha', N'Waiting start')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (4, N'Canvi de format', N'Cambio de formato', N'Format change')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (5, N'Falta comanda', N'Falta comanda', N'Missing order')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (6, N'Esperant caixes', N'Esperando cajas', N'Waiting cases')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (7, N'Restablint', N'Restableciendo', N'Reseting')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (8, N'Esperant lliure', N'Esperando libre', N'Waiting free')
INSERT [dbo].[Info_MXP_Apilador_Info] ([Id], [Ca], [Es], [En]) VALUES (9, N'Apilant caixes', N'Apilando cajas', N'Stacking cases')
