GO
INSERT [dbo].[Info_Paletitzador_Transfer_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1008, N'Forward or reverse speed exceeding the speed limit of the servomotor. Edit parameter box. ', N'Velocitat d''avanç o retrocés superior al límit del servomotor. Modificar paràmetre de la caixa.', N'Vitesse d''avancée ou de recul supérieure à la vitesse limite du servomoteur. Éditer paramètre boîte', N'Velocidad de avance o retroceso superior a la velocidad límite del servomotor. Editar parámetro de caja. ', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Paletitzador_Transfer_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (0, N'UNKNOWN', N'purple', N'Desconegut', N'Desconocido', N'Unknown')
INSERT [dbo].[Info_Paletitzador_Transfer_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (1, N'Suspended', N'#3AC93A', N'Esperant', N'Esperando', N'Waiting')
INSERT [dbo].[Info_Paletitzador_Transfer_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (2, N'STOPPED', N'blue', N'Aturat', N'Parado', N'Stopped')
INSERT [dbo].[Info_Paletitzador_Transfer_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (3, N'RESETING', N'#f9feae', N'Restablint', N'Restableciendo', N'Reseting')
INSERT [dbo].[Info_Paletitzador_Transfer_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (4, N'EXECUTE', N'green', N'En funcionament', N'En funcionamiento', N'Running')
INSERT [dbo].[Info_Paletitzador_Transfer_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (5, N'FORMATCHANGE', N'#fec0df', N'Canvi de format', N'Cambio de formato', N'Format changing')
INSERT [dbo].[Info_Paletitzador_Transfer_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (6, N'ABORTED', N'red', N'Interromput', N'Interrumpido', N'Aborted')
INSERT [dbo].[Info_Paletitzador_Transfer_Estats] ([Id], [Nom], [Color], [Ca], [Es], [En]) VALUES (7, N'HELD', N'yellow', N'Retingut', N'Retenido', N'Held')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (0, N'Desconegut', N'Desconocido', N'Unknown')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (1, N'Interromput per alarma', N'Interrumpido por alarma', N'Aborted by alarm')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (2, N'Falta potència', N'Falta potencia', N'Power off')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (3, N'Falta marxa', N'Falta marcha', N'Waiting start')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (4, N'Canvi de format', N'Cambio de formato', N'Format change')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (5, N'Falta comanda', N'Falta comanda', N'Missing order')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (6, N'Esperant caixes', N'Esperando cajas', N'Waiting cases')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (7, N'Restablint', N'Restableciendo', N'Reseting')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (8, N'Estoc davant', N'Stock delante', N'Stock ahead')
INSERT [dbo].[Info_Paletitzador_Transfer_Info] ([Id], [Ca], [Es], [En]) VALUES (9, N'Transferint caixes', N'Transfiriendo cajas', N'Transferring cases')
