/****** Object:  Table [dbo].[Info_Tancadora_Alarmes]    Script Date: 07/05/2020 10:50:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Info_Tancadores_Alarmes](
	[ID] [int] NOT NULL,
	[en] [varchar](255) NULL,
	[ca] [varchar](255) NULL,
	[fr] [varchar](255) NULL,
	[es] [varchar](255) NULL,
	[grup_en] [varchar](50) NULL,
	[grup_ca] [varchar](50) NULL,
	[grup_fr] [varchar](50) NULL,
	[grup_es] [varchar](50) NULL,
 CONSTRAINT [PK_Info_Tancadores_Alarmes] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Info_Tancadora_Info]    Script Date: 07/05/2020 10:50:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Info_Tancadores_Info](
	[Id] [int] NOT NULL,
	[Ca] [varchar](max) NULL,
	[Es] [varchar](max) NULL,
	[En] [varchar](max) NULL,
 CONSTRAINT [PK_Info_Tancadores_Info] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
GO
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (5, N'Connection failed to block Solenoid CANOpen. Check power and cabling.', N'Ha fallat la connexió CANOpen amb el bloc d''electrovalvules. Revisar alimentació i cablejat.', N'La connexion de CANOpen avec le Bloc d''électrovalves a échoué. Vérifier l''alimentation et le câblage', N'Ha fallado conexión CANOpen con Bloque de Electrovalvulas. Revisar alimentación y cableado.', N'Group general alarms', N'Grup alarmes generals', N'Groupe alarmes générales', N'Grupo alarmas generales')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (6, N'Failed connection to the card input / output. Check wiring and power. ', N'Ha fallat la connexió CANOpen amb tarja d''entrades/sortides. Revisar cablejat i alimentació.', N'La connexion avec la carte d''entrées/sorties a échoué. Vérifier le câblage et l''alimentation', N'Ha fallado conexión con la targeta de entradas/salidas. Revisar cableado y alimentación.', N'Group general alarms', N'Grup alarmes generals', N'Groupe alarmes générales', N'Grupo alarmas generales')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (7, N'Failed connection to the card input / output. Check wiring and power. ', N'Ha fallat la connexió CANOpen amb tarja d''entrades/sortides. Revisar cablejat i alimentació.', N'La connexion avec la carte d''entrées/sorties a échoué. Vérifier le câblage et l''alimentation', N'Ha fallado conexión con la targeta de entradas/salidas. Revisar cableado y alimentación.', N'Group general alarms', N'Grup alarmes generals', N'Groupe alarmes générales', N'Grupo alarmas generales')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (10, N'Check that there is sufficient pressure. Check that the pressure detector is also scheduled (gives a signal only if the pressure is lis higher or lower than the required)', N'Comprovar que hi hagi pressió suficient. Controlar que el detector de pressió estigui ben programat (dóna senyal només si la pressió és inferior o superior a la requerida)', N'Vérifier que la pression est suffisante. Contrôler que le détecteur de pression est bien programmé (il n''émet un signal que si la pression est inférieure ou supérieure à la pression requise)', N'Comprobar que haya presión suficiente. Controlar que el detector de presión esté bién programado (da señal sólo si la presión es inferior o superior a la requerida)', N'Group general alarms', N'Grup alarmes generals', N'Groupe alarmes générales', N'Grupo alarmas generales')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (20, N'Connection failed to block Solenoid Powerlink . Check power and cabling.', N'Ha fallat la connexió Powerlink amb el bloc d''electrovalvules. Revisar alimentació i cablejat.', N'La connexion de Powerlink avec le Bloc d''électrovalves a échoué. Vérifier l''alimentation et le câblage', N'Ha fallado conexión Powerlink con Bloque de Electrovalvulas. Revisar alimentación y cableado.', N'Group general alarms', N'Grup alarmes generals', N'Groupe alarmes générales', N'Grupo alarmas generales')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (21, N'Failed connection to the card input / output. Check wiring and power. ', N'Ha fallat la connexió Powerlink amb tarja d''entrades/sortides. Revisar cablejat i alimentació.', N'La connexion avec la carte d''entrées/sorties a échoué. Vérifier le câblage et l''alimentation', N'Ha fallado conexión con la targeta de entradas/salidas. Revisar cableado y alimentación.', N'Group general alarms', N'Grup alarmes generals', N'Groupe alarmes générales', N'Grupo alarmas generales')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (101, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet.', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier : - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Mould', N'Motlle', N'Moule', N'Molde')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (102, N'Check: - way out. – FD-box forming machine output. - Operation of the ejector arm and suction. - Parameters box.', N'Comprovar: - camí sortida en marxa. - FD sortida Tancadora. - Funcionament braç i ventosa de l''expulsor. - Paràmetres de caixa. ', N'Vérifier : - convoyeur de sortie en marche. - PD sortie formeuse. - Fonctionnement bras et ventouse de l''expulseur. - Paramètres de boîte', N'Comprobar: - camino salida en marcha. - FD salida Tancadora. - Funcionamiento brazo y ventosa del Expulsor. - Parámetros de caja. ', N'Mould', N'Motlle', N'Moule', N'Molde')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (103, N'Check: - Operation vacuum ejector arm - FD in matrix', N'Comprovar: - funcionament braç i ventosa expulsor - FD dins matriu', N'Vérifier: - Fonctionnement bras et ventouse expulseur - PD dans la matrice', N'Comprobar: - Funcionamiento brazo y ventosa expulsor - FD dentro matriz', N'Mould', N'Motlle', N'Moule', N'Molde')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (104, N'Check: - Operation mould - FD in matrix', N'Comprovar: - funcionament motlle - FD dins matriu', N'Vérifier: - Fonctionnement moule - PD dans la matrice', N'Comprobar: - Funcionamiento molde - FD dentro matriz', N'Mould', N'Motlle', N'Moule', N'Molde')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (105, N'Check: - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Mould', N'Motlle', N'Moule', N'Molde')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (106, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Mould', N'Motlle', N'Moule', N'Molde')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (107, N'Mould stop position incorrect. Check mould inverter or reduce degrees of mould brake', N'Comprovar si el valor de la dada fixe del fre del motor del motlle està entre 300 i 320', N'', N'Comprobar si el valor del dato fijo del freno del motor del Molde está entre 300º y 320º', N'Mould', N'Motlle', N'Moule', N'Molde')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (108, N'Some of the magnetic sensors of the mechanisms of subjection of the sheet in the matrix does not give signal. Verify sensors or position of the mechanisms.', N'Algun dels detectors magnètics de la matriu no dona senyal.Verificar detectors o posició mecanismes aguantar la làmina', N'', N'Alguno de los sensores magnéticos de los mecanismos de sujecion de la lámina en la matriz no da señal.Verificar sensores o posición de los mecanismos.', N'Mould', N'Motlle', N'Moule', N'Molde')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (201, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet.', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Ejector', N'Expulsor', N'Expulseur', N'Expulsor')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (202, N'Check: - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Ejector', N'Expulsor', N'Expulseur', N'Expulsor')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (203, N'Check: - FD in matrix - Operation vacuum ejector arm - Box Parameters', N'Comprovar: - FD dins matriu - Funcionament braç i ventosa de l''expulsor - Paràmetres de caixa', N'Vérifier: - PD dans la matrice - Fonctionnement bras et ventouse de l''expulseur - Paramètres de boîte', N'Comprobar: - FD dentro matriz - Funcionamiento brazo y ventosa del expulsor - Parámetros de caja', N'Ejector', N'Expulsor', N'Expulseur', N'Expulsor')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (204, N'Check: - FD at the output ', N'Comprovar: - FD sortida de la Tancadora', N'Vérifier: - FD de sortie', N'Comprobar: - FD de la salida de la Tancadora', N'Ejector', N'Expulsor', N'Expulseur', N'Expulsor')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (206, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Ejector', N'Expulsor', N'Expulseur', N'Expulsor')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (301, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (302, N'Check: - is not heavily loaded feeder sheet - Operation rocker FD - FD feeder operation (if no sheets) - State suction pad', N'Comprovar: - Alimentador no està molt carregat de làmines - Funcionament FD del balancí - Funcionament FD alimentador (si no hi ha làminas) - Estat ventoses', N'Vérifier: - L''alimentateur ne dispose pas de beaucoup de plaques - Fonctionnement PD du balancier - Fonctionnement PD alimentateur (s''il n''y a pas de plaques) - État ventouses', N'Comprobar: - Alimentador no está muy cargado de láminas - Funcionamiento FD del balancín - Funcionamiento FD alimentador (si no hay láminas) - Estado ventosas', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (303, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (304, N'Check: - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (305, N'Check: - Operation rocker sensors - no blanks? ', N'Comprovar: - Funcionament sensors presencia de la lamina de l balanci no hi ha làmines?', N'', N'Comprovar: - Funcionamento sensores presencia de lamina en el balancin no hay laminas?', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (311, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (312, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (313, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (314, N'Check: \ n - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Feeder 1', N'Alimentador 1', N'Alimentateur 1', N'Alimentador 1')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (401, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 2', N'Alimentador 2', N'Alimentateur 2', N'Alimentador 2')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (402, N'Check: - is not heavily loaded feeder sheet - Operation rocker FD - FD feeder operation (if no sheets) - State suction pad', N'Comprovar: - Alimentador no està molt carregat de làmines - Funcionament FD del balancí - Funcionament FD alimentador (si no hi ha làminas) - Estat ventoses', N'Vérifier: - L''alimentateur ne dispose pas de beaucoup de plaques - Fonctionnement PD du balancier -Fonctionnement PD alimentateur (s''il n''y a pas de plaques) - État ventouses', N'Comprobar: - Alimentador no está muy cargado de láminas - Funcionamiento FD del balancín - Funcionamiento FD alimentador (si no hay láminas) - Estado ventosas', N'Feeder 2', N'Alimentador 2', N'Alimentateur 2', N'Alimentador 2')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (403, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Feeder 2', N'Alimentador 2', N'Alimentateur 2', N'Alimentador 2')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (404, N'Check: \ n - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Feeder 2', N'Alimentador 2', N'Alimentateur 2', N'Alimentador 2')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (411, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 2', N'Alimentador 2', N'Alimentateur 2', N'Alimentador 2')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (412, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 2', N'Alimentador 2', N'Alimentateur 2', N'Alimentador 2')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (413, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Feeder 2', N'Alimentador 2', N'Alimentateur 2', N'Alimentador 2')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (414, N'Check: \ n - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Feeder 2', N'Alimentador 2', N'Alimentateur 2', N'Alimentador 2')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (501, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 3', N'Alimentador 3', N'Alimentateur 3', N'Alimentador 3')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (502, N'Check: - is not heavily loaded feeder sheet - Operation rocker FD - FD feeder operation (if no sheets) - State suction pad', N'Comprovar: - Alimentador no està molt carregat de làmines - Funcionament FD del balancí - Funcionament FD alimentador (si no hi ha làminas) - Estat ventoses', N'Vérifier: - L''alimentateur ne dispose pas de beaucoup de plaques - Fonctionnement PD du balancier - Fonctionnement PD alimentateur (s''il n''y a pas de plaques) - État ventouses', N'Comprobar: - Alimentador no está muy cargado de láminas - Funcionamiento FD del balancín - Funcionamiento FD alimentador (si no hay láminas) - Estado ventosas', N'Feeder 3', N'Alimentador 3', N'Alimentateur 3', N'Alimentador 3')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (503, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Feeder 3', N'Alimentador 3', N'Alimentateur 3', N'Alimentador 3')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (504, N'Check: - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Feeder 3', N'Alimentador 3', N'Alimentateur 3', N'Alimentador 3')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (511, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 3', N'Alimentador 3', N'Alimentateur 3', N'Alimentador 3')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (512, N'Check: - is not heavily loaded feeder sheet - Operation rocker FD - FD feeder operation (if no sheets) - State suction pad', N'Comprovar: - Alimentador no està molt carregat de làmines - Funcionament FD del balancí - Funcionament FD alimentador (si no hi ha làminas) - Estat ventoses', N'Vérifier: - L''alimentateur ne dispose pas de beaucoup de plaques - Fonctionnement PD du balancier - Fonctionnement PD alimentateur (s''il n''y a pas de plaques) - État ventouses', N'Comprobar: - Alimentador no está muy cargado de láminas - Funcionamiento FD del balancín - Funcionamiento FD alimentador (si no hay láminas) - Estado ventosas', N'Feeder 3', N'Alimentador 3', N'Alimentateur 3', N'Alimentador 3')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (513, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Feeder 3', N'Alimentador 3', N'Alimentateur 3', N'Alimentador 3')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (514, N'Check: \ n - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Feeder 3', N'Alimentador 3', N'Alimentateur 3', N'Alimentador 3')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (601, N'Check: - wired encoder - encoder parameters - State module I / O of the cabinet', N'Comprovar: - cablejat encoder - paràmetres de l''encoder - Estat mòdul E/S de l''armari.', N'Vérifier: - câblage encoder - paramètres de l''encoder - État module E/S de l''armoire', N'Comprobar: - cableado encoder - parámetros del encoder - Estado módulo E/S del armario.', N'Feeder 4', N'Alimentador 4', N'Alimentateur 4', N'Alimentador 4')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (602, N'Check: - is not heavily loaded feeder sheet - Operation rocker FD - FD feeder operation (if no sheets) - State suction pad', N'Comprovar: - Alimentador no està molt carregat de làmines - Funcionament FD del balancí - Funcionament FD alimentador (si no hi ha làminas) - Estat ventoses', N'Vérifier: - L''alimentateur ne dispose pas de beaucoup de plaques - Fonctionnement PD du balancier - Fonctionnement PD alimentateur (s''il n''y a pas de plaques) - État ventouses', N'Comprobar: - Alimentador no está muy cargado de láminas - Funcionamiento FD del balancín - Funcionamiento FD alimentador (si no hay láminas) - Estado ventosas', N'Feeder 4', N'Alimentador 4', N'Alimentateur 4', N'Alimentador 4')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (603, N'If the Inverter error is not reset, power off', N'Si no es reseteja l''error del variador, treure la tensió', N'Si l''erreur du variateur ne fait pas un reset, déconnecter la tension', N'Si no se resetea el error del variador, sacar la tensión', N'Feeder 4', N'Alimentador 4', N'Alimentateur 4', N'Alimentador 4')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (604, N'Check: - Operating motor - State of the encoder - State module I / O cabinet ', N'Comprovar: - Funcionament motor - Estat de l''encoder - Estat mòdul E/S de l''armari', N'Vérifier: - Fonctionnement moteur - État de l''encoder - État module E/S de l''armoire', N'Comprobar: - Funcionamiento motor - Estado del encoder - Estado módulo E/S del armario', N'Feeder 4', N'Alimentador 4', N'Alimentateur 4', N'Alimentador 4')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (700, N'Unknown Error. Check manual', N'Error del servo no filtrat. Consultar manual.', N'Erreur de servo non filtré. Consulter le manuel', N'Error de servo no filtrado. Consultar manual.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (701, N'Detects positive or negative limit. Remove manually the servo shoe position. Check operation of the detectors. ', N'Detecta limit positiu o negatiu. Treure manualment el patí de la posició limit. Comprovar funcionament dels detectors.', N'Il détecte la limite positive ou négative. Enlever le patin de sa position manuellement . Vérifier le Fonctionnement des détecteurs', N'Detecta limite positivo o negativo. Sacar manualmente el patín de la posición. Comprovar funcionamiento de los detectores.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (702, N'Check wiring', N'Revisar cablejat', N'Vérifier le câblage', N'Revisar cableado', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (703, N'Check: - Data fixed machine - Box Parameters', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifier: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (704, N'Check: - Data fixed machine - Box Parameters', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifier: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (705, N'Check: - Data fixed machine - Box Parameters ', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifier: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (706, N'Failed servo shoe control power. Check wiring and restart the machine. ', N'Ha fallat l''alimentació de control del servo. Reiniciar la màquina.', N'L''alimentation de contrôle du servo a échoué. Vérifier le câblage et relancer la machine', N'Ha fallado la alimentación de control del servo. Revisar cableado y reiniciar la maquina.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (707, N'Failed communication PLC-servo shoe. Restarting PLC.', N'Ha fallat comunicació autòmat-patí. Reiniciar autòmat.', N'La communication automate-patin a échoué. Vérifier l''automate', N'Ha fallado comunicación autómata-patín. Reiniciar autómata.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (708, N'Forward or reverse speed exceeding the speed limit of the servomotor. Edit parameter box. ', N'Velocitat d''avanç o retrocés superior al límit del servomotor. Modificar paràmetre de la caixa.', N'Vitesse d''avancée ou de recul supérieure à la vitesse limite du servomoteur. Éditer paramètre boîte', N'Velocidad de avance o retroceso superior a la velocidad límite del servomotor. Editar parámetro de caja. ', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (711, N'It was expected that the servo was referenced. Check servo configuration. ', N'S''esperava que el servo es referenciés. Comprovar configuració del servo.', N'Le référencement du servo était attendue. Vérifier configuration du servo.', N'Se esperaba que el servo se referenciara. Comprobar configuración del servo.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (720, N'The servo shoe has not reached the desired position. Restart Machine. ', N'El patí no ha arribat a la posició desitjada. Reiniciar Màquina.', N'Le patin n''a pas atteint la position souhaitée. Réinitialiser la machine.', N'El patín no ha llegado a la posición deseada. Reiniciar Máquina.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (721, N'The position of closing clamp can not be longer than the left position of the sheet. Check fixed data of box forming machine and parameters of the sheet. ', N'La posició de tancar pinça no pot ser superior a la posició de deixada de la làmina. Comprovar dades fixes de la Tancadora i els paràmetres de làmina. ', N'La position de fermeture de la pince ne peut pas être supérieure à la position de dépôt de la plaque. Vérifier les données fixes de la formeuse et les paramètres de la plaque.', N'La posición de cerrar pinza no puede ser superior a la posición de dejada de la lámina. Comprobar datos fijos de laTancadora y los parámetros de la lámina.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (730, N'Remove the sheet on the guides. Check position of the sheets in the feeder. ', N'Treure la làmina sobre les guies. Comprovar posició de les làmines a l''alimentador.', N'Enlever la plaque sur les guides. Vérifier la position des plaques dans l''alimentateur.', N'Sacar la lámina sobre las guías. Comprobar posición de las láminas en el alimentador.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (731, N'Remove the sheet on the guides. Check position of the sheets in the feeder. ', N'Treure la làmina sobre les guies. Comprovar posició de les làmines a l''alimentador.', N'Enlever la plaque sur les guides. Vérifier la position des plaques dans l''alimentateur.', N'Sacar la lámina sobre las guías. Comprobar posición de las láminas en el alimentador.', N'Servo shoe', N'Servo patí', N'Servo patin', N'Servo patín')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (811, N'Check: - Data fixed machine - Box Parameters', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifer: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (812, N'Press again Start Manoeuvre', N'Torna a apretar inici de maniobra.', N'Réessayer le lancement de la machine', N'Vuelve a intentar inicio de maniobra.', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (813, N'Press again Start Manoeuvre', N'Torna a apretar inici de maniobra.', N'Réessayer le lancement de la machine', N'Vuelve a intentar inicio de maniobra.', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (814, N'Check motor and power wiring. (Located in the arm glue) ', N'Revisar cablejat i alimetació del motor. (motor situat en el braç encolador)', N'Vérifier le câblage et l''alimentation du moteur. (situé sur le bras de l''encolleuse)', N'Revisar cableado i alimentación del motor. (situado en el brazo encolador)', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (815, N'Check: - Data fixed machine - Box Parameters', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifer: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (816, N'Unknown Error. Check manual', N'Error no filtrat. Consultar manual.', N'Erreur non filtrée. Consulter le manuel.', N'Error no filtrado. Consultar manual.', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (817, N'Start maneuver to equalize the widths', N'Iniciar la maniobra per igualar les amplades', N'Lancer la manœuvre pour égaliser les largeurs', N'Iniciar la maniobra para igualar las anchuras', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (818, N'Start maneuver to equalize the widths', N'Iniciar la maniobra per igualar les amplades', N'Lancer la manœuvre pour égaliser les largeurs', N'Iniciar la maniobra para igualar las anchuras', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (819, N'Start maneuver to equalize lengths', N'Iniciar la maniobra per igualar les llargades', N'Lancer la manœuvre pour égaliser les longueurs', N'Iniciar la maniobra para igualar las longitudes', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (820, N'Start maneuver to equalize lengths', N'Iniciar la maniobra per igualar les llargades', N'Lancer la manœuvre pour égaliser les longueurs', N'Iniciar la maniobra para igualar las longitudes', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (821, N'Check: - Data fixed machine - Box Parameters', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifer: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (822, N'Press Start Manoeuvre again', N'Torna a apretar inici de maniobra.', N'Réessayer le lancement de la machine', N'Vuelve a intentar inicio de maniobra.', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (823, N'Press Start Manoeuvre again', N'Torna a apretar inici de maniobra.', N'Réessayer le lancement de la machine', N'Vuelve a intentar inicio de maniobra.', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (824, N'Check motor and power wiring. (Located in the arm glue) ', N'Revisar cablejat i alimentació del motor. (motor situat en el braç encolador)', N'Vérifier le câblage et l''alimentation du moteur. (situé sur le bras de l''encolleuse)', N'Revisar cableado i alimentación del motor. (situado brazo encolador)', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (825, N'Check: - Data fixed machine - Box Parameters', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifer: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (826, N'Revise boxes data or check collision length-guides parameter', N'Provable valor incorrecte dades fixes colisions guies llargada o dades de caixa ', N'', N'Conflicto colision guias-longitud. Revisar datos fijos colision guias longitud o medidas de caja. ', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (828, N'Start maneuver to equalize the guides', N'Iniciar la maniobra per igualar les guies', N'Lancer la manœuvre pour égaliser les guides', N'Iniciar la maniobra para igualar las guias', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (830, N'Start maneuver to equalize the guides', N'Iniciar la maniobra per igualar les guies', N'Lancer la manœuvre pour égaliser les guides', N'Iniciar la maniobra para igualar las guias', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (831, N'Length and width incompatibility', N'Incompatibilitat llargada i amplada', N'', N'Incompatibilidad longitud y anchura', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (832, N'Length and width incompatibility', N'Incompatibilitat llargada i amplada', N'', N'Incompatibilidad longitud y anchura', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (833, N'Unknown Error. Check manual', N'Error no filtrat. Consultar manual.', N'Erreur non filtrée. Consulter le manuel.', N'Error no filtrado. Consultar manual.', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (834, N'Revise boxes data or check collision length-guns parameter', N'Provable valor incorrecte dades fixes colisions guies pistoles o dades de caixa ', N'', N'Conflicto colision guias-pistolas. Revisar datos fijos colision guias pistolas o medidas de caja. ', N'Iclas', N'Iclas', N'Iclas', N'Iclas')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (901, N'Remove the sheets on the feeder before you change the format. Check feeder1 FD ', N'Descarregar les làmines de l''alimentador abans de fer canvi de format.Comprovar FD alimentador1.', N'Décharger les plaques de l''alimentateur avant de faire le changement de format.Vérifier PD alimentateur 1', N'Descargar las laminas del alimentador antes de hacer cambio de formato.Comprobar FD alimentador1', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (902, N'Box in matrix trying to change the format. Remove the sheet of the matrix before returning to start to change the format. Check FD in matrix. ', N'Caixa dins matriu a l''intentar canvi de format.Treure la caixa de la matriu abans del canvi de format.Comprovar FD dins matriu.', N'Boîte dans la matrice lors de la tentative de changement de format.Enlever la boîte de la matrice avant de relancer le changement de format.Vérifier PD dans la matrice', N'Caja dentro matriz al intentar cambio de formato.Sacar la caja de la matriz antes de volver a iniciar cambio de formato.Comprobar FD dentro matriz.', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (903, N'Box on guides trying to change the format. Remove the sheet before returning to start to change the format. Check FD', N'Làmina sobre guies a l''intentar canvi de format.Treure la làmina de les guies abans del canvi de format.Comprovar FD', N'Plaque sur les guides lors de la tentative de changement de format.Enlever la plaque sur les guides avant de relancer le changement de format.Vérifier PD', N'Lámina sobre guías al intentar cambio de formato.Sacar la lámina de las guías antes de volver a iniciar cambio de formato.Comprobar FD', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (904, N'Expected end of the movement of the motors to change the format and have not finished. Check: - state detectors - Performance engines ', N'S''esperava fi del moviment dels motors de canvi de format i no han finalitzat.Comprovar: - Estat detectors - Funcionament motors', N'La fin du mouvement des moteurs de changement de format était attendue et il n''a pas finalisé.Vérifier: - État détecteurs - Fonctionnement moteurs', N'Se esperaba fin del movimiento de los motores de cambio de formato y no han finalizado.Comprobar: - Estado detectores - Funcionamiento motores', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (905, N'Box in tabs folder trying to change the format. Remove the sheet of the tabs folder before returning to start to change the format. Check FD in tabs folder. ', N'Caixa dins plegador a l''intentar canvi de format.Treure la caixa del plegador abans del canvi de format.Comprovar FD plegador.', N'', N'Caja en el plegador al intentar cambio de formato.Sacar la caja del plegador antes de volver a iniciar cambio de formato.Comprobar FD plegador.', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (906, N'Select correct box in feeder 1', N'Seleccionar caja correcta en alimentador 1', N'', N'Seleccionar caja correcta en alimentador 1', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (907, N'Select correct box in feeder 2', N'Seleccionar caja correcta en alimentador 2', N'', N'Seleccionar caja correcta en alimentador 2', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (950, N'Interruption/Quick-Stop by Homing detector.', N'Revisar el detector de homing de l''IclA que no detecti.', N'', N'Revisar el detector de Homing del Icla que no detecte.', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1000, N'Unknown Error. Check manual', N'Error del servo no filtrat. Consultar manual.', N'Erreur de servo non filtré. Consulter le manuel', N'Error de servo no filtrado. Consultar manual.', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1001, N'Detects positive or negative limit.Check operation of the detectors. ', N'Detecta limit positiu o negatiu. Comprovar funcionament dels detectors.', N'Il détecte la limite positive ou négative. Vérifier le Fonctionnement des détecteurs', N'Detecta limite positivo o negativo. Comprovar funcionamiento de los detectores.', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1002, N'Check wiring', N'Revisar cablejat', N'Vérifier le câblage', N'Revisar cableado', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1003, N'Check: - Data fixed machine - Box Parameters', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifier: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1004, N'Check: - Data fixed machine - Box Parameters', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifier: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1005, N'Check: - Data fixed machine - Box Parameters ', N'Comprovar: - Dades fixes máquina - Paràmetres de caixa', N'Vérifier: - Données fixes machine - Paramètres de boîte', N'Comprobar: - Datos fijos máquina - Parámetros de caja', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1006, N'Failed servo shoe control power. Check wiring and restart the machine. ', N'Ha fallat l''alimentació de control del servo. Reiniciar la màquina.', N'L''alimentation de contrôle du servo a échoué. Vérifier le câblage et relancer la machine', N'Ha fallado la alimentación de control del servo. Revisar cableado y reiniciar la maquina.', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1007, N'Failed communication PLC-servo mould. Restarting PLC.', N'Ha fallat comunicació autòmat-Motlle. Reiniciar autòmat.', N'La communication automate-molde a échoué. Vérifier l''automate', N'Ha fallado comunicación autómata-Molde. Reiniciar autómata.', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
GO
INSERT [dbo].[Info_Tancadores_Alarmes] ([ID], [en], [ca], [fr], [es], [grup_en], [grup_ca], [grup_fr], [grup_es]) VALUES (1008, N'Forward or reverse speed exceeding the speed limit of the servomotor. Edit parameter box. ', N'Velocitat d''avanç o retrocés superior al límit del servomotor. Modificar paràmetre de la caixa.', N'Vitesse d''avancée ou de recul supérieure à la vitesse limite du servomoteur. Éditer paramètre boîte', N'Velocidad de avance o retroceso superior a la velocidad límite del servomotor. Editar parámetro de caja. ', N'Feeder management', N'Gestió alimentadors', N'Gestion alimentateurs', N'Gestión alimentadores')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (0, N'Desconegut', N'Desconocido', N'Unknown')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (1, N'Interromput per alarma', N'Interrumpido por alarma', N'Aborted by alarm')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (2, N'Falta potència', N'Falta potencia', N'Power off')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (3, N'Falta marxa', N'Falta marcha', N'Waiting start')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (4, N'Canvi de format', N'Cambio de formato', N'Format change')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (5, N'Falta comanda', N'Falta comanda', N'Missing order')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (6, N'Esperant caixes', N'Esperando cajas', N'Waiting cases')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (7, N'Restablint', N'Restableciendo', N'Reseting')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (8, N'Estoc davant', N'Stock delante', N'Stock ahead')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (9, N'Tancant caixes', N'Cerrando cajas', N'Closing cases')
INSERT [dbo].[Info_Tancadores_Info] ([Id], [Ca], [Es], [En]) VALUES (10, N'Esperant encolador', N'Esperando encolador', N'Waiting gluer')
GO
